services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todosql
    build:
        context: server
        dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: server
    depends_on:
      - postgres
    command: bash -c "/usr/local/bin/setup.sh"
volumes:
  postgres_data:
